import { defineField, defineType } from 'sanity'
// Reusing HeartFilledIcon (also used by Donate Settings) rather than a less
// certain icon name — @sanity/icons' exact export list couldn't be checked
// against a live package install in this environment (see project README).
import { HeartFilledIcon } from '@sanity/icons/HeartFilled'

// A server-written payment log, not editorial content: `/api/donate` creates
// one of these (status "pending") the moment a Cyberpay hosted-cashier
// session is opened, and `/api/donate/webhook` patches it to the final
// status once Cyberpay confirms the payment. It exists so the donate
// thank-you page (which only gets `merchantReference` back on the redirect,
// not `transactionId`) has something to look up, and so the Foundation has
// a record of donations without needing a separate database. Editors can
// view/annotate these in the Studio but should not need to create them by
// hand in normal operation.
export const donation = defineType({
  name: 'donation',
  title: 'Donation',
  type: 'document',
  icon: HeartFilledIcon,
  fields: [
    defineField({
      name: 'merchantReference',
      title: 'Merchant reference',
      type: 'string',
      description: 'Generated by the site when the donor starts checkout. Used to look this record up from the thank-you page.',
      validation: (rule) => rule.required(),
      readOnly: true,
    }),
    defineField({
      name: 'transactionId',
      title: 'Cyberpay transaction ID',
      type: 'string',
      description: 'Filled in once Cyberpay creates the payment session.',
      readOnly: true,
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          { title: 'Pending', value: 'pending' },
          { title: 'Completed', value: 'completed' },
          { title: 'Declined', value: 'declined' },
          { title: 'Refunded', value: 'refunded' },
        ],
        layout: 'radio',
      },
      initialValue: 'pending',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'amount',
      title: 'Amount',
      type: 'number',
      readOnly: true,
    }),
    defineField({
      name: 'currency',
      title: 'Currency',
      type: 'string',
      readOnly: true,
    }),
    defineField({
      name: 'donorName',
      title: 'Donor name',
      type: 'string',
      readOnly: true,
    }),
    defineField({
      name: 'donorEmail',
      title: 'Donor email',
      type: 'string',
      readOnly: true,
    }),
    defineField({
      name: 'designation',
      title: 'Directed to',
      type: 'string',
      description: 'What the donor asked their gift to be directed toward, e.g. "Where it is needed most".',
      readOnly: true,
    }),
    defineField({
      name: 'cyberpayMethod',
      title: 'Payment method used',
      type: 'string',
      description: 'e.g. "Card", "Bank Transfer" — filled in from the webhook payload.',
      readOnly: true,
    }),
    defineField({
      name: 'createdAt',
      title: 'Created',
      type: 'datetime',
      readOnly: true,
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: 'confirmedAt',
      title: 'Confirmed',
      type: 'datetime',
      description: 'Set when the webhook first reports a non-pending status.',
      readOnly: true,
    }),
  ],
  orderings: [
    {
      title: 'Created, new to old',
      name: 'createdAtDesc',
      by: [{ field: 'createdAt', direction: 'desc' }],
    },
  ],
  preview: {
    select: { amount: 'amount', currency: 'currency', status: 'status', donorEmail: 'donorEmail' },
    prepare: ({ amount, currency, status, donorEmail }) => ({
      title: `${currency || ''} ${amount ?? '—'}`.trim(),
      subtitle: `${status || 'pending'} · ${donorEmail || 'no email'}`,
    }),
  },
})
