/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type HeroSection = {
  _type: "heroSection";
  eyebrow?: string;
  heading: string;
  body?: string;
  image: CreditedImage;
  primaryCta?: CtaLink;
  secondaryCta?: CtaLink;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CreditedImage = {
  _type: "creditedImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  credit?: string;
};

export type FocusArea = {
  _type: "focusArea";
  title: string;
  description: string;
};

export type Stat = {
  _type: "stat";
  value: string;
  label: string;
};

export type FooterColumn = {
  _type: "footerColumn";
  heading: string;
  links?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type NavLink = {
  _type: "navLink";
  label: string;
  href: string;
};

export type CtaLink = {
  _type: "ctaLink";
  label: string;
  href: string;
};

export type Enquiry = {
  _id: string;
  _type: "enquiry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email: string;
  phone?: string;
  topic?:
    | "general"
    | "membership"
    | "scholarships"
    | "partnership"
    | "education"
    | "healthcare"
    | "culture"
    | "livelihoods"
    | "community";
  supportType?: string;
  message?: string;
  status?: "new" | "actioned";
  submittedAt?: string;
};

export type NewsletterSubscriber = {
  _id: string;
  _type: "newsletterSubscriber";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email: string;
  subscribedAt?: string;
};

export type NewsEventsPage = {
  _id: string;
  _type: "newsEventsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading: string;
  newsletterHeading?: string;
  newsletterBody?: string;
};

export type ProgrammesPage = {
  _id: string;
  _type: "programmesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading: string;
  intro?: string;
};

export type DonatePage = {
  _id: string;
  _type: "donatePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading: string;
  intro?: string;
  givingTiers?: Array<{
    amount: string;
    description: string;
    _type: "givingTier";
    _key: string;
  }>;
  otherWaysToGive?: Array<string>;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading: string;
  intro?: string;
  secretariatAddress?: string;
  scholarshipsEmail?: string;
  partnershipsEmail?: string;
  mapImage?: CreditedImage;
};

export type LeadershipPage = {
  _id: string;
  _type: "leadershipPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading: string;
  intro?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  group: "trustees" | "executive";
  photo?: CreditedImage;
  order?: number;
};

export type ProjectsImpactPage = {
  _id: string;
  _type: "projectsImpactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading: string;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ref: string;
  title: string;
  area: string;
  location: string;
  year: number;
  status: "Ongoing" | "Completed";
  description?: string;
  image?: CreditedImage;
  featured?: boolean;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading: string;
  intro?: string;
  storyImage?: CreditedImage;
  storyHeading?: string;
  storyParagraphs?: Array<string>;
  aimsHeading?: string;
  aimsIntro?: string;
  aims?: Array<string>;
};

export type Donation = {
  _id: string;
  _type: "donation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  merchantReference: string;
  transactionId?: string;
  status: "pending" | "completed" | "declined" | "refunded";
  amount?: number;
  currency?: string;
  donorName?: string;
  donorEmail?: string;
  designation?: string;
  cyberpayMethod?: string;
  createdAt?: string;
  confirmedAt?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  date: string;
  location?: string;
};

export type NewsItem = {
  _id: string;
  _type: "newsItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  publishedAt: string;
  excerpt?: string;
};

export type Programme = {
  _id: string;
  _type: "programme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  category: string;
  description: string;
  image: CreditedImage;
  featuredOnHome?: boolean;
  order?: number;
};

export type DonateSettings = {
  _id: string;
  _type: "donateSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading: string;
  body?: string;
  note?: string;
  currency?: "NGN";
  suggestedAmounts?: Array<number>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: CreditedImage;
  siteName: string;
  siteNameSub?: string;
  logoInitials?: string;
  navLinks?: Array<
    {
      _key: string;
    } & NavLink
  >;
  footerTagline?: string;
  footerColumns?: Array<
    {
      _key: string;
    } & FooterColumn
  >;
  legalName?: string;
  contactAddress?: string;
  contactEmail?: string;
  contactPhone?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: HeroSection;
  visionEyebrow?: string;
  visionStatement: string;
  missionEyebrow?: string;
  missionStatement: string;
  missionNote?: string;
  missionCta?: CtaLink;
  focusAreas?: Array<
    {
      _key: string;
    } & FocusArea
  >;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | HeroSection
  | SanityImageAssetReference
  | CreditedImage
  | FocusArea
  | Stat
  | FooterColumn
  | NavLink
  | CtaLink
  | Enquiry
  | NewsletterSubscriber
  | NewsEventsPage
  | ProgrammesPage
  | DonatePage
  | ContactPage
  | LeadershipPage
  | Person
  | ProjectsImpactPage
  | Project
  | AboutPage
  | Donation
  | Event
  | NewsItem
  | Programme
  | DonateSettings
  | SiteSettings
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../web/src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    hero{      eyebrow,      heading,      body,      image {  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  credit,  hotspot,  crop},      primaryCta { label, href },      secondaryCta { label, href }    },    visionEyebrow,    visionStatement,    missionEyebrow,    missionStatement,    missionNote,    missionCta { label, href },    focusAreas[]{ _key, title, description },    stats[]{ _key, value, label }  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      hero: null;
      visionEyebrow: null;
      visionStatement: null;
      missionEyebrow: null;
      missionStatement: null;
      missionNote: null;
      missionCta: null;
      focusAreas: null;
      stats: null;
    }
  | {
      hero: null;
      visionEyebrow: null;
      visionStatement: null;
      missionEyebrow: null;
      missionStatement: null;
      missionNote: null;
      missionCta: null;
      focusAreas: null;
      stats: Array<{
        _key: string;
        value: string;
        label: string;
      }> | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        heading: string;
        body: string | null;
        image: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
              } | null;
            } | null;
          } | null;
          alt: string;
          credit: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        };
        primaryCta: {
          label: string;
          href: string;
        } | null;
        secondaryCta: {
          label: string;
          href: string;
        } | null;
      } | null;
      visionEyebrow: string | null;
      visionStatement: string;
      missionEyebrow: string | null;
      missionStatement: string;
      missionNote: string | null;
      missionCta: {
        label: string;
        href: string;
      } | null;
      focusAreas: Array<{
        _key: string;
        title: string;
        description: string;
      }> | null;
      stats: Array<{
        _key: string;
        value: string;
        label: string;
      }> | null;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    logo {  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  credit,  hotspot,  crop},    siteName,    siteNameSub,    logoInitials,    navLinks[]{ _key, label, href },    footerTagline,    footerColumns[]{      _key,      heading,      links[]{ _key, label, href }    },    legalName,    contactAddress,    contactEmail,    contactPhone  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      logo: null;
      siteName: null;
      siteNameSub: null;
      logoInitials: null;
      navLinks: null;
      footerTagline: null;
      footerColumns: null;
      legalName: null;
      contactAddress: null;
      contactEmail: null;
      contactPhone: null;
    }
  | {
      logo: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
            } | null;
          } | null;
        } | null;
        alt: string;
        credit: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      siteName: string;
      siteNameSub: string | null;
      logoInitials: string | null;
      navLinks: Array<{
        _key: string;
        label: string;
        href: string;
      }> | null;
      footerTagline: string | null;
      footerColumns: Array<{
        _key: string;
        heading: string;
        links: Array<{
          _key: string;
          label: string;
          href: string;
        }> | null;
      }> | null;
      legalName: string | null;
      contactAddress: string | null;
      contactEmail: string | null;
      contactPhone: string | null;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: DONATE_SETTINGS_QUERY
// Query: *[_id == "donateSettings"][0]{    heading,    body,    note,    currency,    suggestedAmounts  }
export type DONATE_SETTINGS_QUERY_RESULT =
  | {
      heading: null;
      body: null;
      note: null;
      currency: null;
      suggestedAmounts: null;
    }
  | {
      heading: string;
      body: null;
      note: null;
      currency: null;
      suggestedAmounts: null;
    }
  | {
      heading: null;
      body: null;
      note: null;
      currency: string | null;
      suggestedAmounts: null;
    }
  | {
      heading: string;
      body: string | null;
      note: string | null;
      currency: "NGN" | null;
      suggestedAmounts: Array<number> | null;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: FEATURED_PROGRAMMES_QUERY
// Query: *[_type == "programme" && featuredOnHome == true] | order(order asc) [0...3]{    _id,    title,    category,    description,    image {  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  credit,  hotspot,  crop}  }
export type FEATURED_PROGRAMMES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  category: string;
  description: string;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    credit: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: LATEST_NEWS_QUERY
// Query: *[_type == "newsItem"] | order(publishedAt desc) [0...3]{    _id,    title,    publishedAt,    excerpt  }
export type LATEST_NEWS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  publishedAt: string;
  excerpt: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: UPCOMING_EVENTS_QUERY
// Query: *[_type == "event" && date >= now()] | order(date asc) [0...2]{    _id,    title,    date,    location  }
export type UPCOMING_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  date: string;
  location: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_id == "aboutPage"][0]{    eyebrow,    heading,    intro,    storyImage {  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  credit,  hotspot,  crop},    storyHeading,    storyParagraphs,    aimsHeading,    aimsIntro,    aims  }
export type ABOUT_PAGE_QUERY_RESULT =
  | {
      eyebrow: null;
      heading: null;
      intro: null;
      storyImage: null;
      storyHeading: null;
      storyParagraphs: null;
      aimsHeading: null;
      aimsIntro: null;
      aims: null;
    }
  | {
      eyebrow: null;
      heading: string;
      intro: null;
      storyImage: null;
      storyHeading: null;
      storyParagraphs: null;
      aimsHeading: null;
      aimsIntro: null;
      aims: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      intro: null;
      storyImage: null;
      storyHeading: null;
      storyParagraphs: null;
      aimsHeading: null;
      aimsIntro: null;
      aims: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      intro: string | null;
      storyImage: null;
      storyHeading: null;
      storyParagraphs: null;
      aimsHeading: null;
      aimsIntro: null;
      aims: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      intro: string | null;
      storyImage: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
            } | null;
          } | null;
        } | null;
        alt: string;
        credit: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      storyHeading: string | null;
      storyParagraphs: Array<string> | null;
      aimsHeading: string | null;
      aimsIntro: string | null;
      aims: Array<string> | null;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: PROGRAMMES_PAGE_QUERY
// Query: *[_id == "programmesPage"][0]{ eyebrow, heading, intro }
export type PROGRAMMES_PAGE_QUERY_RESULT =
  | {
      eyebrow: null;
      heading: null;
      intro: null;
    }
  | {
      eyebrow: null;
      heading: string;
      intro: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      intro: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      intro: string | null;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: ALL_PROGRAMMES_QUERY
// Query: *[_type == "programme"] | order(order asc){    _id,    title,    category,    description,    image {  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  credit,  hotspot,  crop}  }
export type ALL_PROGRAMMES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  category: string;
  description: string;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    credit: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: PROJECTS_IMPACT_PAGE_QUERY
// Query: *[_id == "projectsImpactPage"][0]{    eyebrow,    heading,    stats[]{ _key, value, label }  }
export type PROJECTS_IMPACT_PAGE_QUERY_RESULT =
  | {
      eyebrow: null;
      heading: null;
      stats: null;
    }
  | {
      eyebrow: null;
      heading: null;
      stats: Array<{
        _key: string;
        value: string;
        label: string;
      }> | null;
    }
  | {
      eyebrow: null;
      heading: string;
      stats: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      stats: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      stats: Array<{
        _key: string;
        value: string;
        label: string;
      }> | null;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && featured == true] | order(year desc) [0...2]{    _id,    ref,    title,    area,    location,    year,    description,    image {  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  credit,  hotspot,  crop}  }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  ref: string;
  title: string;
  area: string;
  location: string;
  year: number;
  description: string | null;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    credit: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: ALL_PROJECTS_QUERY
// Query: *[_type == "project"] | order(year desc, ref desc){    _id,    ref,    title,    area,    location,    year,    status  }
export type ALL_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  ref: string;
  title: string;
  area: string;
  location: string;
  year: number;
  status: "Completed" | "Ongoing";
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: NEWS_EVENTS_PAGE_QUERY
// Query: *[_id == "newsEventsPage"][0]{ heading, newsletterHeading, newsletterBody }
export type NEWS_EVENTS_PAGE_QUERY_RESULT =
  | {
      heading: null;
      newsletterHeading: null;
      newsletterBody: null;
    }
  | {
      heading: string;
      newsletterHeading: null;
      newsletterBody: null;
    }
  | {
      heading: string;
      newsletterHeading: string | null;
      newsletterBody: string | null;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: ALL_NEWS_QUERY
// Query: *[_type == "newsItem"] | order(publishedAt desc){    _id,    title,    publishedAt,    excerpt  }
export type ALL_NEWS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  publishedAt: string;
  excerpt: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: ALL_UPCOMING_EVENTS_QUERY
// Query: *[_type == "event" && date >= now()] | order(date asc){    _id,    title,    date,    location  }
export type ALL_UPCOMING_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  date: string;
  location: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: DONATE_PAGE_QUERY
// Query: *[_id == "donatePage"][0]{    eyebrow,    heading,    intro,    givingTiers[]{ amount, description },    otherWaysToGive  }
export type DONATE_PAGE_QUERY_RESULT =
  | {
      eyebrow: null;
      heading: null;
      intro: null;
      givingTiers: null;
      otherWaysToGive: null;
    }
  | {
      eyebrow: null;
      heading: string;
      intro: null;
      givingTiers: null;
      otherWaysToGive: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      intro: null;
      givingTiers: null;
      otherWaysToGive: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      intro: string | null;
      givingTiers: null;
      otherWaysToGive: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      intro: string | null;
      givingTiers: Array<{
        amount: string;
        description: string;
      }> | null;
      otherWaysToGive: Array<string> | null;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: LEADERSHIP_PAGE_QUERY
// Query: *[_id == "leadershipPage"][0]{ eyebrow, heading, intro }
export type LEADERSHIP_PAGE_QUERY_RESULT =
  | {
      eyebrow: null;
      heading: null;
      intro: null;
    }
  | {
      eyebrow: null;
      heading: string;
      intro: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      intro: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      intro: string | null;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: PEOPLE_QUERY
// Query: *[_type == "person"] | order(group asc, order asc){    _id,    name,    role,    group,    photo {  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  credit,  hotspot,  crop}  }
export type PEOPLE_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  role: string;
  group: "executive" | "trustees";
  photo: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    credit: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_id == "contactPage"][0]{    eyebrow,    heading,    intro,    secretariatAddress,    scholarshipsEmail,    partnershipsEmail,    mapImage {  asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  credit,  hotspot,  crop}  }
export type CONTACT_PAGE_QUERY_RESULT =
  | {
      eyebrow: null;
      heading: null;
      intro: null;
      secretariatAddress: null;
      scholarshipsEmail: null;
      partnershipsEmail: null;
      mapImage: null;
    }
  | {
      eyebrow: null;
      heading: string;
      intro: null;
      secretariatAddress: null;
      scholarshipsEmail: null;
      partnershipsEmail: null;
      mapImage: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      intro: null;
      secretariatAddress: null;
      scholarshipsEmail: null;
      partnershipsEmail: null;
      mapImage: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      intro: string | null;
      secretariatAddress: null;
      scholarshipsEmail: null;
      partnershipsEmail: null;
      mapImage: null;
    }
  | {
      eyebrow: string | null;
      heading: string;
      intro: string | null;
      secretariatAddress: string | null;
      scholarshipsEmail: string | null;
      partnershipsEmail: string | null;
      mapImage: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
            } | null;
          } | null;
        } | null;
        alt: string;
        credit: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
    }
  | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_id == "homePage"][0]{\n    hero{\n      eyebrow,\n      heading,\n      body,\n      image {\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  credit,\n  hotspot,\n  crop\n},\n      primaryCta { label, href },\n      secondaryCta { label, href }\n    },\n    visionEyebrow,\n    visionStatement,\n    missionEyebrow,\n    missionStatement,\n    missionNote,\n    missionCta { label, href },\n    focusAreas[]{ _key, title, description },\n    stats[]{ _key, value, label }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_id == "siteSettings"][0]{\n    logo {\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  credit,\n  hotspot,\n  crop\n},\n    siteName,\n    siteNameSub,\n    logoInitials,\n    navLinks[]{ _key, label, href },\n    footerTagline,\n    footerColumns[]{\n      _key,\n      heading,\n      links[]{ _key, label, href }\n    },\n    legalName,\n    contactAddress,\n    contactEmail,\n    contactPhone\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_id == "donateSettings"][0]{\n    heading,\n    body,\n    note,\n    currency,\n    suggestedAmounts\n  }\n': DONATE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "programme" && featuredOnHome == true] | order(order asc) [0...3]{\n    _id,\n    title,\n    category,\n    description,\n    image {\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  credit,\n  hotspot,\n  crop\n}\n  }\n': FEATURED_PROGRAMMES_QUERY_RESULT;
    '\n  *[_type == "newsItem"] | order(publishedAt desc) [0...3]{\n    _id,\n    title,\n    publishedAt,\n    excerpt\n  }\n': LATEST_NEWS_QUERY_RESULT;
    '\n  *[_type == "event" && date >= now()] | order(date asc) [0...2]{\n    _id,\n    title,\n    date,\n    location\n  }\n': UPCOMING_EVENTS_QUERY_RESULT;
    '\n  *[_id == "aboutPage"][0]{\n    eyebrow,\n    heading,\n    intro,\n    storyImage {\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  credit,\n  hotspot,\n  crop\n},\n    storyHeading,\n    storyParagraphs,\n    aimsHeading,\n    aimsIntro,\n    aims\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_id == "programmesPage"][0]{ eyebrow, heading, intro }\n': PROGRAMMES_PAGE_QUERY_RESULT;
    '\n  *[_type == "programme"] | order(order asc){\n    _id,\n    title,\n    category,\n    description,\n    image {\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  credit,\n  hotspot,\n  crop\n}\n  }\n': ALL_PROGRAMMES_QUERY_RESULT;
    '\n  *[_id == "projectsImpactPage"][0]{\n    eyebrow,\n    heading,\n    stats[]{ _key, value, label }\n  }\n': PROJECTS_IMPACT_PAGE_QUERY_RESULT;
    '\n  *[_type == "project" && featured == true] | order(year desc) [0...2]{\n    _id,\n    ref,\n    title,\n    area,\n    location,\n    year,\n    description,\n    image {\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  credit,\n  hotspot,\n  crop\n}\n  }\n': FEATURED_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project"] | order(year desc, ref desc){\n    _id,\n    ref,\n    title,\n    area,\n    location,\n    year,\n    status\n  }\n': ALL_PROJECTS_QUERY_RESULT;
    '\n  *[_id == "newsEventsPage"][0]{ heading, newsletterHeading, newsletterBody }\n': NEWS_EVENTS_PAGE_QUERY_RESULT;
    '\n  *[_type == "newsItem"] | order(publishedAt desc){\n    _id,\n    title,\n    publishedAt,\n    excerpt\n  }\n': ALL_NEWS_QUERY_RESULT;
    '\n  *[_type == "event" && date >= now()] | order(date asc){\n    _id,\n    title,\n    date,\n    location\n  }\n': ALL_UPCOMING_EVENTS_QUERY_RESULT;
    '\n  *[_id == "donatePage"][0]{\n    eyebrow,\n    heading,\n    intro,\n    givingTiers[]{ amount, description },\n    otherWaysToGive\n  }\n': DONATE_PAGE_QUERY_RESULT;
    '\n  *[_id == "leadershipPage"][0]{ eyebrow, heading, intro }\n': LEADERSHIP_PAGE_QUERY_RESULT;
    '\n  *[_type == "person"] | order(group asc, order asc){\n    _id,\n    name,\n    role,\n    group,\n    photo {\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  credit,\n  hotspot,\n  crop\n}\n  }\n': PEOPLE_QUERY_RESULT;
    '\n  *[_id == "contactPage"][0]{\n    eyebrow,\n    heading,\n    intro,\n    secretariatAddress,\n    scholarshipsEmail,\n    partnershipsEmail,\n    mapImage {\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  credit,\n  hotspot,\n  crop\n}\n  }\n': CONTACT_PAGE_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
